### ISSUE TITLE
Local running instruction

### ISSUE THREAD

**Issue by Rajan** [Metnew/React-Koa-Rethink#1]
This is a great setup and I'd like to use for a new project.
I ran using "sudo npm start" and ran into this at the browser:

No Authorization header found

Can you add instructions to run this locally?

**Comment by Metnew** [comment]
Sorry, but this setup isn't ready now. I'll finish it in next few days(2-3 days). "No Authorization header found" -  result of using "koa-jwt" for all application requests. I have second repo with frontend part for this project, that will be merged here. Thanks for issue.

**Comment by Metnew** [comment]
7bc35d1 fix some your issues, more info you can find in [Readme](https://github.com/Metnew/koa-graphql-rethinkdb-starter/blob/master/README.md). Contributions are welcome.

**Comment by Rajan** [comment]
I'm playing with this. It has Marco templating engine and angular in the frontend, Koa/rethink in the backend. Check it out for real-time apps. What are your thoughts?

https://github.com/knowthen/Episode-10-Building-realtime-web-applications

**Comment by Metnew** [comment]
IMHO - it's a good, comparably old, small example - angular 1.x isn't a trend now, koa version is old. This app just shows a possibilities of Koa, Socket.io, Rethinkdb. Also, there is good example of [connection to Rethinkdb](https://github.com/knowthen/Episode-10-Building-realtime-web-applications/blob/master/dash.js).

**Comment by Rajan** [comment]
Are we targeting the web too? How is our new example relevant in Bootstrap
4.0 scenario?

**Comment by Rajan** [comment]
React and Bootstrap 4: https://github.com/reactstrap/reactstrap

**Comment by Metnew** [comment]
Sorry, I didn't get that - _"Are we targeting the web too?"_. 
Hm, Reactstrap is interesting project, thanks for link. Changing Material.ui to Reactstrap won't change the project stability, cause it's just frontend packs of react elements, if you asked about that. Reactstrap or something similar will be added to Yeoman generator.

**Comment by Rajan** [comment]
The interesting thing about Marco is that it updates (diff patches the DOM without the virtual part) and I guess that's faster than doing the react/virtual-dom for web-apps at least.

**Comment by Metnew** [comment]
Marco is server-side rendering engine, am I right? Isn't client-side?

**Comment by Rajan** [comment]
It does both.

> Marko is a really fast and lightweight HTML-based templating engine that compiles templates to readable Node.js-compatible JavaScript modules, and it works on the server and in the browser.

**Comment by Metnew** [comment]
Oh, cool, thnx.
